require: rubocop-sketchup

AllCops:
  DisplayCopNames: true
  Exclude:
    - 'src/*/vendor/**/*'
  SketchUp:
    TargetSketchUpVersion: 2017

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

# Aim for 10 lines and less in each methods but accept slightly longer ones.
Metrics/MethodLength:
  Max: 20

# Need to use camelCase for SketchUp API, otherwise use snake_case.
Naming/MethodName:
  Enabled: false

# x, y and z used by SketchUp API.
Naming/UncommunicativeMethodParamName:
  AllowedNames:
    - 'x'
    - 'y'
    - 'z'
    - '_x'
    - '_y'
    - '_z'

Layout/AlignHash:
  EnforcedColonStyle: table

# Let Git client handle file endings.
Layout/EndOfLine:
  Enabled: false

# False positive when there is an empty line between require, using etc and
# first method.
Layout/EmptyLinesAroundModuleBody:
  Enabled: false
Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/IndentArray:
  EnforcedStyle: consistent
Layout/IndentHash:
  EnforcedStyle: consistent

# False positives for modules documented in one file but not another, e.g.
# extension wrapper.
Style/Documentation:
  Enabled: false

# Double negation is a handy Ruby idiom to assure a value is a boolean, as there
# is no to_bool/to_boolean/to_b method. What the cop suggest, !var.nil?, doesn't
# even cater for boolean false as input.
Style/DoubleNegation:
  Enabled: false

# Single quotes being faster is hardly measurable and only affects parse time.
# Enforcing double quotes reduces the times where you need to change them
# when introducing an interpolation. Use single quotes only if their semantics
# are needed.
Style/StringLiterals:
  EnforcedStyle: double_quotes

SketchupDeprecations:
  Enabled: true

SketchupPerformance:
  Enabled: true

SketchupRequirements:
  Enabled: true

SketchupSuggestions:
  Enabled: true
